name: Publish Python Package

on:
  push:
    tags:
      - 'v*'        # Match tags for production releases
      - 'test-*'    # Match tags for test releases

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      # pip install setuptools wheel twine

    - name: Configure Poetry Authentication
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        # Only needed if you publish to Test PyPI
        poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Build package
      run: |
        poetry build

    - name: Publish to Test PyPI
      if: startsWith(github.ref, 'refs/tags/test-')
      run: |
        poetry publish --repository testpypi

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        poetry publish