name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install -r requirements.txt
    
    - name: Install dependencies
      run: |
        poetry install

    - name: Install dependencies including optional dependencies
      run: |
        python -m pip install toml
        EXTRAS=$(python .github/workflows/extract_extra_deps.py)
        echo "EXTRAS=$EXTRAS"
        poetry install $EXTRAS

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run Flake8
      run: poetry run flake8 polymind/

    - name: Run isort
      run: poetry run isort --check-only .
    
    # Set fake environment variables for openai
    - name: Set environment variables
      run: |
        echo "OPENAI_API_KEY=fake-api-key" >> $GITHUB_ENV
        echo "VECTOR_DB_HOST=fake-host" >> $GITHUB_ENV
        echo "VECTOR_DB_PORT=fake-port" >> $GITHUB_ENV
        echo "TAVILY_API_KEY=fake-api-key" >> $GITHUB_ENV

    - name: Run Pytest
      run: poetry run pytest -vv --cov=polymind --cov-config=pyproject.toml -vv tests
